// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC531Vs9Bqq7ww0kZoJLqMnWcQiuGeUerE',
    appId: '1:356946228565:android:2b3d6a94ee01eded1c6bdc',
    messagingSenderId: '356946228565',
    projectId: 'phone-otp-1ff2c',
    storageBucket: 'phone-otp-1ff2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6b4LXbly3rem3o9uRtljuW3AkGs8tn9w',
    appId: '1:356946228565:ios:0ea4e5bddab575ef1c6bdc',
    messagingSenderId: '356946228565',
    projectId: 'phone-otp-1ff2c',
    storageBucket: 'phone-otp-1ff2c.appspot.com',
    androidClientId: '356946228565-99p1ikhg3ai5bqd3mklf7toubva1flup.apps.googleusercontent.com',
    iosClientId: '356946228565-6tjl4tt9kc8qknjch33i27vmnm3ppkev.apps.googleusercontent.com',
    iosBundleId: 'com.example.heartdiseasePred',
  );
}
